services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: timestampdb
    ports:
      - "3306:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD-SHELL", "mysql -h localhost -uroot -padmin -e 'SELECT 1'" ]
      interval: 5s
      retries: 5
      timeout: 5s

  goapp:
    build: ./goapp
    depends_on:
      mysql:
        condition: service_healthy
    restart: on-failure
    ports:
      - 8080:8080

  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend/static:/usr/share/nginx/html:ro
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - goapp
    restart: on-failure

volumes:
  mysql-data:
