services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: timestampdb
    ports:
      - "3306:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-padmin" ]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 30s
  goapp:
    build: ./goapp
    depends_on:
      mysql:
        condition: service_healthy
    restart: on-failure

volumes:
  mysql-data:
