services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: timestampdb
    ports:
      - "3306:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
  goapp:
    build: ./goapp
    depends_on:
      - mysql
    restart: on-failure

volumes:
  mysql-data:
